[package]
name = "esp32dev-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
dioxus = { version = "^0.7", features = ["web", "router"] }
dioxus-logger = "^0.7"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
gloo-timers = { version = "0.3", features = ["futures"] }

[workspace]
members = ["src-tauri"]
